services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data:/app/data

  frontend:
      build:
        context: .
        dockerfile: Dockerfile.frontend
      ports:
        - "3000:3000"
      depends_on:
        - backend
