FROM node:20.17.0 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY backend/package*.json ./

RUN npm install

COPY backend/ .

# Rebuild SQLite3 and other native modules
RUN npm rebuild

RUN npm run build

FROM node:20.17.0-slim

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3001

CMD ["node", "dist/index.js"]
